Internal Server Error: /checkout/wh/
Traceback (most recent call last):
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\stripe\_stripe_object.py", line 170, in __getattr__
    return self[k]
           ~~~~^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\stripe\_stripe_object.py", line 212, in __getitem__
    raise err
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\stripe\_stripe_object.py", line 200, in __getitem__
    return super(StripeObject, self).__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'charges'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\checkout\webhooks.py", line 56, in webhook
    response = event_handler(event)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\checkout\webhook_handler.py", line 33, in handle_payment_intent_succeeded
    billing_details = intent.charges.data[0].billing_details
                      ^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\stripe\_stripe_object.py", line 172, in __getattr__
    raise AttributeError(*err.args) from err
AttributeError: charges
"POST /checkout/wh/ HTTP/1.1" 500 124303
Internal Server Error: /checkout/wh/
Traceback (most recent call last):
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\stripe\_stripe_object.py", line 170, in __getattr__
    return self[k]
           ~~~~^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\stripe\_stripe_object.py", line 212, in __getitem__
    raise err
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\stripe\_stripe_object.py", line 200, in __getitem__
    return super(StripeObject, self).__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'bag'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\checkout\webhooks.py", line 56, in webhook
    response = event_handler(event)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\checkout\webhook_handler.py", line 30, in handle_payment_intent_succeeded
    bag = intent.metadata.bag
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hijaz\Documents\vscode-projects\Portfolio3\boutique_ado_v1\.venv\Lib\site-packages\stripe\_stripe_object.py", line 172, in __getattr__
    raise AttributeError(*err.args) from err
AttributeError: bag
"POST /checkout/wh/ HTTP/1.1" 500 110413
